### ISSUE TITLE
need help with CDRZabbixGLPI

### ISSUE THREAD

**Issue by StefanSa** [firetxelo/CDRZabbixGLPI#1]
hi @firetxelo
Can you help me with the installation of your plugin for CDRZabbixGLPI.

i user zabbix v5.2

Following question:
What conditions should be used for action?
In action operation / recovery operation i don't have the option of "remote command", what do I have to do here?

Thanks in advance
StefanS

**Comment by firetxelo** [comment]
The condition can be trigger severity. I used to create a ticket for problems that are high or disaster severity

Remote command options is in operation type field

![image](https://user-images.githubusercontent.com/35845033/99389326-a22d4700-28b5-11eb-85cc-fa0221154508.png)

![image](https://user-images.githubusercontent.com/35845033/99389350-aeb19f80-28b5-11eb-928f-06d31f64b4c7.png)

**Comment by StefanSa** [comment]
@firetxelo, ahhh perfect.

**Comment by firetxelo** [comment]
Let me know yout feedback

**Comment by StefanSa** [comment]
@firetxelo 
hmm i get this error, any help here ?
```
usage: CDRZabbixGLPI.py [-h] [-a ACTION] [-e EVENTID] [-n EVENTNAME]
[-o HOSTNAME] [-t TRIGGERID]
CDRZabbixGLPI.py: error: unrecognized arguments: Inventory Service (OCS Inventory Service) is not running (startup type automatic)
```

![external_command](https://user-images.githubusercontent.com/6105075/99531307-d3377580-29a2-11eb-9b0e-32e9d69192b5.png)

**Comment by firetxelo** [comment]
Look at reports > action log...

How the command was executed e post here please

**Comment by StefanSa** [comment]
OK, there are problems with the quotation marks, here is one too many or one is missing.
```
Zabbix server:/usr/bin/python3 /opt/CDRZabbixGLPI.py -a create -e 169 -n ""OCS Inventory Service" (OCS Inventory Service) is not running (startup type automatic)" -o "SFG05" -t 17564
```

**Comment by firetxelo** [comment]
yes... Change de action to -n '{EVENT.NAME}' ... single quotes

**Comment by StefanSa** [comment]
Now, i get a new error.
```
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw)
File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/lib64/python3.6/http/client.py", line 1262, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1308, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1257, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
self.send(msg)
File "/usr/lib64/python3.6/http/client.py", line 974, in send
self.connect()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
conn = self._new_conn()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f24fd67dac8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/us
```

```
Zabbix server:/usr/bin/python3 /opt/CDRZabbixGLPI.py -a create -e 174 -n '"OCS Inventory Service" (OCS Inventory Service) is not running (startup type automatic)' -o "SFG05" -t 17564
```

**Comment by firetxelo** [comment]
I can't recognize this error. It looks like something related to connection. If you try to run the command manually does it give an error? Remembering that to run the command by hand, the problem must be active.

**Comment by StefanSa** [comment]
Sorry, it was my mistake, had entered the wrong URL.

```
Traceback (most recent call last):
File "/opt/CDRZabbixGLPI.py", line 138, in <module>
create_ticket(args.eventid)
File "/opt/CDRZabbixGLPI.py", line 67, in create_ticket
session_token = (init_session())
File "/opt/CDRZabbixGLPI.py", line 46, in init_session
return res_dict['session_token']
TypeError: list indices must be integers or slices, not str
```
```
Zabbix server:/usr/bin/python3 /opt/CDRZabbixGLPI.py -a create -e 176 -n '"OCS Inventory Service" (OCS Inventory Service) is not running (startup type automatic)' -o "SFG05" -t 17564
```

**Comment by firetxelo** [comment]
TypeError: list indices must be integers or slices, not str

This happens when the script can t get the session_token. Take sure that the tokens informed are correct. 

The user token is APP TOKEN in user management

**Comment by StefanSa** [comment]
Again for clarification.
GLPI_TOKEN = GLPI APP token on setup> General> API
This is the API client App_Tocken

What do you mean by "User token on this format ->" user_token GLPIUSERTOKEN "
Greetings to Brazil?

**Comment by firetxelo** [comment]
In the request that script do to the API, it have to send "user_token" before the token. It's the way that de API works.

So if your token is bEtF6Sy4RbIWAp607XhEEXbodBbXVuQLqN855PjE

![image](https://user-images.githubusercontent.com/35845033/99557100-0f69d680-29a1-11eb-9214-90d65353d2c7.png)

so that variable must be "user_token bEtF6Sy4RbIWAp607XhEEXbodBbXVuQLqN855PjE"


I m from Brazil... and you?

**Comment by StefanSa** [comment]
@firetxelo 
Thanks again for your help.
Ticket is now created but not deleted.
```
172.16.34.54 - - [20/Nov/2020:14:28:55 +0100] "GET /apirest.php/search/Ticket?is_deleted=0&as_map=0&criteria[0][link]=AND&criteria[0][field]=1&criteria
[0][searchtype]=contains&criteria[0][value]=[ZBX-250]&search=Pesquisar&itemtype=Ticket HTTP/1.1" 200 312 "-" "python-requests/2.20.1"
172.16.34.54 - - [20/Nov/2020:14:28:55 +0100] "GET /apirest.php/killSession HTTP/1.1" 200 - "-" "python-requests/2.20.1"
172.16.34.54 - - [20/Nov/2020:14:28:55 +0100] "GET /apirest.php/initSession HTTP/1.1" 200 46 "-" "python-requests/2.20.1"
172.16.34.54 - - [20/Nov/2020:14:28:55 +0100] "POST /apirest.php/itilsolution/ HTTP/1.1" 400 101 "-" "python-requests/2.20.1"
172.16.34.54 - - [20/Nov/2020:14:28:55 +0100] "GET /apirest.php/killSession HTTP/1.1" 200 - "-" "python-requests/2.20.1"
```

**Comment by firetxelo** [comment]
The script does not delete the ticket. It updates the ticket to solved status and add a itil solution. 

Your GLPI_SOLUTION_ID is a valid ID?

**Comment by StefanSa** [comment]
@firetxelo 
Sorry for the late reply.
Can you please explain this on the basis of a screen shoot.
`ID of a created type of ticket solution. When ticket is closed, the script use this solution type`
Thanks for your time and greetings to Brazil.

**Comment by firetxelo** [comment]
When you interact with a ticket there is one tab called solution. The script add a solution on this tab of related ticket. Try to do it manually, the script do the same.

If you want that the ticket do that with a specific solution type, you have to inform the ID

**Comment by StefanSa** [comment]
Hmm,
a solution type with the ID "1" exists, but the script does not update GLPI because it cannot find it (error 400).
![sltype](https://user-images.githubusercontent.com/6105075/100515086-ea801b00-3179-11eb-9663-f4a74c7b7203.PNG)

**Comment by firetxelo** [comment]
I have to look into your system to find the problem.

**Comment by StefanSa** [comment]
thank you for your help.
the problem was due to the insufficient authorization of the API user. Now it works without a problem.
i still have one question, could you extend your plugin so that it sends html text to glpi?

Thanks for your time and greetings to Brazil.

**Comment by StefanSa** [comment]
i found a solution self.
