### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by pereirasamuel** [firetxelo/CDRZabbixGLPI#2]
Saudações!
Vi em outro Issue que você é brasileiro, por isso vou falar em português mesmo. Mas, se for o caso é só dizer que falo em inglês.

Então, configurei tudo como pedido! Porém está dando o seguinte erro:

File "/etc/zabbix/scripts/glpi-ticket.py", line 91
    "name": f"[ZBX-{eventid}] - {eventname} - {hostname}",
                                                                                         ^
SyntaxError: invalid syntax

Qual será o problema?

**Comment by firetxelo** [comment]
Boa noite...

Geralmente esse erro se dá pela versão do python que voce ta utilizado. Essa sintaxe só é permitida do python 3.6 em diante se não me engano.

**Comment by GuiBalestro** [comment]
Olá,
Como não houve feedback estou confirmando que esse erro ocorre devido a versão do python que é chamada na criação da acão.

Tive o mesmo erro usando Debian 10, instalei o python3.9, pip3 e seguindo as orientações do script.

Na ação criei diferente pois deixei em outro caminho, mas isso fica a crietério de cada um.

/usr/local/bin/python3.9 /etc/zabbix/scripts/CDRZabbixGLPI.py -a create -e {EVENT.ID} -n '{EVENT.NAME}' -o "{HOST.NAME}" -t {TRIGGER.ID}


Obrigado @firetxelo por compartilhar.
-------------------------------------


Editando:
Com o python3.9 resolveu o erro de syntax, porém não consegui finalizar a integração pois ocorria o erro:

Traceback (most recent call last):
File "/etc/zabbix/scripts/CDRZabbixGLPI.py", line 138, in
create_ticket(args.eventid)
File "/etc/zabbix/scripts/CDRZabbixGLPI.py", line 73, in create_ticket
severity = zbx_problem_severity(triggerid)
File "/etc/zabbix/scripts/CDRZabbixGLPI.py", line 60, in zbx_problem_severity
with ZabbixAPI(url=ZabbixURL, user=ZabbixUser, password=ZabbixPass) as zapi:
TypeError: init() got an unexpected keyword argument 'url'

Consegui finalizar a integração com sucesso após usar o python 3.7.3 que já vem instalado no Debian 10.

Para mim a ação ficou:

/usr/bin/python3 /etc/zabbix/scripts/CDRZabbixGLPI.py -a create -e {EVENT.ID} -n '{EVENT.NAME}' -o "{HOST.NAME}" -t {TRIGGER.ID}

Para saber onde está localizado o python executar: which python3
Para saber a versão: python3 --version
