### ISSUE TITLE
feature request, disable ssl url check

### ISSUE THREAD

**Issue by StefanSa** [firetxelo/CDRZabbixGLPI#4]
Hi @firetxelo 
I hope you are doing well in Brazil.
In the meantime, glpi / zabbix have been switch to https and run in a kubernetes cluster.
It is not that easy to implement the root-ca here. So it would be good to have an option to bypass this error message:

`certificate verify failed`

Thanks for your help and time.

**Comment by firetxelo** [comment]
This is a flag on requests call
