### ISSUE TITLE
String indices must be integers

### ISSUE THREAD

**Issue by selectsolucoes** [firetxelo/CDRZabbixGLPI#5]
Olá @firetxelo, tudo bem?

Não estou conseguindo implementar a integração, já passei pelas issues comentadas aqui e agora estou travado com esse erro, você consegue me ajudar?

 File "/usr/lib/zabbix/externalscripts/zabbix-glpi-root.py", line 140, in <module>
    create_ticket(args.eventid)
  File "/usr/lib/zabbix/externalscripts/zabbix-glpi-root.py", line 99, in create_ticket
    zapi.event.acknowledge(eventids=eventid, action=6, message=f"Ticket ID on GLPÌ: {json.loads(r.text)[0]['id']}")
TypeError: string indices must be integers

Obrigado.

**Comment by firetxelo** [comment]
o token esta errado

**Comment by selectsolucoes** [comment]
Obrigado @firetxelo!

Descobri que na verdade meu GLPI não está respondendo o initSession.

Estou na 9.5.4

**Comment by selectsolucoes** [comment]
Atualizei para ultima versão a 9.5.5, mas mesmo assim não resolveu! 
Pesquisando na web confirmei que existem outros usuários com a mesma lentidão com a geração da sessão! 
Uma das soluções encontradas pelos usuários foi mudar o authorization de user_token para basic.
Gerei minha hash base64 através do comando 
# echo -n usuario:senha | base64 

E no script
DE:
GLPI_AUTH_TOKEN = os.getenv('GLPI_USER_AUTH_TOKEN', "user_token HBzTJ6EbQTxsf7PzwbZjaTYqAzJs5H2vSLp1PXzi")
PARA
GLPI_AUTH_TOKEN = os.getenv('GLPI_USER_AUTH_TOKEN', "Basic dXN1YXJpbzpzZW5oYQ==")

Funcionou pra mim! =)
